In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3,4],
           [5,6,7,8],
           [2,4,6,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 4, 6, 8]])

In [6]:
b=np.array([[1,3,5,7],
   [9,8,7,6],
   [4,3,2,1]])
b

array([[1, 3, 5, 7],
       [9, 8, 7, 6],
       [4, 3, 2, 1]])

In [4]:
#Display no. of dimensions of matrix
a.ndim

2

In [7]:
b.ndim

2

In [8]:
#shape of matrix
a.shape

(3, 4)

In [9]:
b.shape


(3, 4)

In [10]:
# a+b
np.add(a,b)

array([[ 2,  5,  8, 11],
       [14, 14, 14, 14],
       [ 6,  7,  8,  9]])

In [11]:
# a-b
np.subtract(a,b)

array([[ 0, -1, -2, -3],
       [-4, -2,  0,  2],
       [-2,  1,  4,  7]])

In [12]:
 # a*b(elementwise)
 a*b   

array([[ 1,  6, 15, 28],
       [45, 48, 49, 48],
       [ 8, 12, 12,  8]])

In [16]:
#Matrix multiplication 
np.matmul(a,a.T)

array([[ 30,  70,  60],
       [ 70, 174, 140],
       [ 60, 140, 120]])

In [17]:
#add 10 to all elements of a
np.add(a,10)

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [12, 14, 16, 18]])

In [18]:
# transpose of b
b.T

array([[1, 9, 4],
       [3, 8, 3],
       [5, 7, 2],
       [7, 6, 1]])

In [19]:
#average,mean and standard deviation of b
np.average(b)

4.666666666666667

In [22]:
np.mean(b)

4.666666666666667

In [21]:
np.std(b)

2.6246692913372702

In [23]:
#  the maximum element in each column and each row of the matrix a
np.max(a,axis=0)

array([5, 6, 7, 8])

In [24]:
np.max(a,axis=1)

array([4, 8, 8])

In [25]:
# minimum value of matrix b
np.min(b)

1

In [27]:
# reshaping b as 2x6
b.reshape(2,6)

array([[1, 3, 5, 7, 9, 8],
       [7, 6, 4, 3, 2, 1]])

In [28]:
# transpose of a
a.T

array([[1, 5, 2],
       [2, 6, 4],
       [3, 7, 6],
       [4, 8, 8]])

In [29]:
# Creating row vector
row_a=np.array([5,10,15])
row_a


array([ 5, 10, 15])

In [30]:
# Creating column vector
col_a=np.array([[5],
               [10],
               [15]])
col_a

array([[ 5],
       [10],
       [15]])

In [33]:
# Transpose of column vector
col_a.T

array([[ 5, 10, 15]])

In [34]:
np.add(row_a,col_a)

array([[10, 15, 20],
       [15, 20, 25],
       [20, 25, 30]])

In [35]:
# creating dictionary of data
dict1={1:'A',2:'B',3:'C',4:'D'}
dict1

{1: 'A', 2: 'B', 3: 'C', 4: 'D'}

In [28]:
ls=list(dict1.items())
ls

[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')]

In [36]:
# converting dictionary to feature matrix
arr=np.array(ls)
arr

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D']], dtype='<U11')

In [34]:
# column names
dict1.keys()

dict_keys([1, 2, 3, 4])