In [20]:
import numpy as np
import pandas as pd
from pprint import pprint

In [21]:
dataset=pd.read_csv("Downloads/winequality-red.csv" , sep=';')
dataset

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [4]:
dim=dataset.shape
dim

(1599, 12)

In [5]:
dataset.head(11)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0             7.4              0.70         0.00             1.9      0.076   
1             7.8              0.88         0.00             2.6      0.098   
2             7.8              0.76         0.04             2.3      0.092   
3            11.2              0.28         0.56             1.9      0.075   
4             7.4              0.70         0.00             1.9      0.076   
5             7.4              0.66         0.00             1.8      0.075   
6             7.9              0.60         0.06             1.6      0.069   
7             7.3              0.65         0.00             1.2      0.065   
8             7.8              0.58         0.02             2.0      0.073   
9             7.5              0.50         0.36             6.1      0.071   
10            6.7              0.58         0.08             1.8      0.097   

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                  11.0                  34.0   0.9978  3.51       0.56   
1                  25.0                  67.0   0.9968  3.20       0.68   
2                  15.0                  54.0   0.9970  3.26       0.65   
3                  17.0                  60.0   0.9980  3.16       0.58   
4                  11.0                  34.0   0.9978  3.51       0.56   
5                  13.0                  40.0   0.9978  3.51       0.56   
6                  15.0                  59.0   0.9964  3.30       0.46   
7                  15.0                  21.0   0.9946  3.39       0.47   
8                   9.0                  18.0   0.9968  3.36       0.57   
9                  17.0                 102.0   0.9978  3.35       0.80   
10                 15.0                  65.0   0.9959  3.28       0.54   

    alcohol  quality  
0       9.4        5  
1       9.8        5  
2       9.8        5  
3       9.8        6  
4       9.4        5  
5       9.4        5  
6       9.4        5  
7      10.0        7  
8       9.5        7  
9      10.5        5  
10      9.2        5

In [6]:
dataset.loc[dataset["quality"]<5,"quality"]=0
dataset.loc[dataset["quality"]==5,"quality"]=1
dataset.loc[dataset["quality"]==6,"quality"]=1
dataset.loc[dataset["quality"]>6,"quality"]=2

In [7]:
dataset.head(11)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0             7.4              0.70         0.00             1.9      0.076   
1             7.8              0.88         0.00             2.6      0.098   
2             7.8              0.76         0.04             2.3      0.092   
3            11.2              0.28         0.56             1.9      0.075   
4             7.4              0.70         0.00             1.9      0.076   
5             7.4              0.66         0.00             1.8      0.075   
6             7.9              0.60         0.06             1.6      0.069   
7             7.3              0.65         0.00             1.2      0.065   
8             7.8              0.58         0.02             2.0      0.073   
9             7.5              0.50         0.36             6.1      0.071   
10            6.7              0.58         0.08             1.8      0.097   

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                  11.0                  34.0   0.9978  3.51       0.56   
1                  25.0                  67.0   0.9968  3.20       0.68   
2                  15.0                  54.0   0.9970  3.26       0.65   
3                  17.0                  60.0   0.9980  3.16       0.58   
4                  11.0                  34.0   0.9978  3.51       0.56   
5                  13.0                  40.0   0.9978  3.51       0.56   
6                  15.0                  59.0   0.9964  3.30       0.46   
7                  15.0                  21.0   0.9946  3.39       0.47   
8                   9.0                  18.0   0.9968  3.36       0.57   
9                  17.0                 102.0   0.9978  3.35       0.80   
10                 15.0                  65.0   0.9959  3.28       0.54   

    alcohol  quality  
0       9.4        1  
1       9.8        1  
2       9.8        1  
3       9.8        1  
4       9.4        1  
5       9.4        1  
6       9.4        1  
7      10.0        2  
8       9.5        2  
9      10.5        1  
10      9.2        1

In [8]:
#function to perform z score normalization
def normalize(old_x):
    new_x=((old_x-np.mean(old_x))/np.std(old_x))
    return new_x


In [9]:
dataset.iloc[:,0:11]=dataset.iloc[:,0:11].apply(normalize)
dataset.head(11)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0       -0.528360          0.961877    -1.391472       -0.453218  -0.243707   
1       -0.298547          1.967442    -1.391472        0.043416   0.223875   
2       -0.298547          1.297065    -1.186070       -0.169427   0.096353   
3        1.654856         -1.384443     1.484154       -0.453218  -0.264960   
4       -0.528360          0.961877    -1.391472       -0.453218  -0.243707   
5       -0.528360          0.738418    -1.391472       -0.524166  -0.264960   
6       -0.241094          0.403229    -1.083370       -0.666062  -0.392483   
7       -0.585813          0.682553    -1.391472       -0.949853  -0.477498   
8       -0.298547          0.291499    -1.288771       -0.382271  -0.307468   
9       -0.470907         -0.155419     0.457144        2.526589  -0.349975   
10      -0.930531          0.291499    -0.980669       -0.524166   0.202621   

    free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0             -0.466193             -0.379133  0.558274  1.288643  -0.579207   
1              0.872638              0.624363  0.028261 -0.719933   0.128950   
2             -0.083669              0.229047  0.134264 -0.331177  -0.048089   
3              0.107592              0.411500  0.664277 -0.979104  -0.461180   
4             -0.466193             -0.379133  0.558274  1.288643  -0.579207   
5             -0.274931             -0.196679  0.558274  1.288643  -0.579207   
6             -0.083669              0.381091 -0.183745 -0.072005  -1.169337   
7             -0.083669             -0.774449 -1.137769  0.511130  -1.110324   
8             -0.657454             -0.865676  0.028261  0.316751  -0.520193   
9              0.107592              1.688677  0.558274  0.251958   0.837107   
10            -0.083669              0.563545 -0.448752 -0.201591  -0.697233   

     alcohol  quality  
0  -0.960246        1  
1  -0.584777        1  
2  -0.584777        1  
3  -0.584777        1  
4  -0.960246        1  
5  -0.960246        1  
6  -0.960246        1  
7  -0.397043        2  
8  -0.866379        2  
9   0.072294        1  
10 -1.147981        1

In [10]:
bin_labels=[0,1,2,3]
for i in range(0,11):
    dataset.iloc[:,i]=pd.qcut(dataset.iloc[:,i],q=4,labels=bin_labels)
dataset.head(11)

fixed acidity volatile acidity citric acid residual sugar chlorides  \
0              1                3           0              0         1   
1              1                3           0              2         3   
2              1                3           0              2         3   
3              3                0           3              0         1   
4              1                3           0              0         1   
5              1                3           0              0         1   
6              1                2           0              0         0   
7              1                3           0              0         0   
8              1                2           0              1         1   
9              1                1           2              3         1   
10             0                2           0              0         3   

   free sulfur dioxide total sulfur dioxide density pH sulphates alcohol  \
0                    1                    1       2  3         1       0   
1                    3                    3       2  0         2       1   
2                    2                    2       2  1         2       1   
3                    2                    2       3  0         1       1   
4                    1                    1       2  3         1       0   
5                    1                    2       2  3         1       0   
6                    2                    2       1  1         0       0   
7                    2                    0       0  2         0       1   
8                    1                    0       2  2         1       0   
9                    2                    3       2  2         3       2   
10                   2                    3       1  1         0       0   

    quality  
0         1  
1         1  
2         1  
3         1  
4         1  
5         1  
6         1  
7         2  
8         2  
9         1  
10        1

In [11]:
trcount=int(dataset.shape[0]*0.8)
trcount

1279

In [12]:
#function to split training and test data
def train_test_split(dataset):
    trdata=dataset.iloc[:trcount].reset_index(drop=True)
    tsdata=dataset.iloc[trcount:].reset_index(drop=True)
    return trdata,tsdata
trdata=train_test_split(dataset)[0]
tsdata=train_test_split(dataset)[1]

In [13]:
trdata.shape

(1279, 12)

In [14]:
tsdata.shape

(320, 12)

In [15]:
#fuction to calculate entropy using 'unique' method
def entropy(class_label_data):
    values,counts=np.unique(class_label_data,return_counts=True)
    for i in range(len(values)):
        # -Pi log2 Pi
        entropy=np.sum([(-counts[i]/np.sum(counts))*np.log2(counts[i]/np.sum(counts))])
    return entropy

In [16]:
#calculating information gain
def infogain(data,split_attribute_name,class_label="quality"):
    total_entropy=entropy(data[class_label])
    vals,counts=np.unique(data[split_attribute_name],return_counts=True)
    #weighted entropy
    for i in range(len(vals)):
        weighted_entropy=np.sum([(counts[i]/np.sum(counts))*entropy(data.where(data[split_attribute_name]==vals[i]).dropna()[class_label])])
    information_gain=total_entropy-weighted_entropy
    return information_gain


In [17]:
# implementing decision tree algorithm
def ID3(data,originaldata,features,class_label="quality",parent_node_class=None):
    # if all class_label has same value,return the value
    if len(np.unique(data[class_label]))<=1:
        return np.unique(data[class_label])[0]
    
    # if dataset is empty or below some threshold value,then terminate recursion
    elif len(data)==0:
        return np.unique(originaldata[class_label])[np.argmax(np.unique(originaldata[class_label],return_counts=True)[1])]
    
    # if feature space is empty,then terminate recursion
    elif len(features)==0:
        return parent_node_class
    
    #form subtrees if all conditions mentioned above are false
    else:
        # majority class label
        parent_node_class=np.unique(data[class_label])[np.argmax(np.unique(data[class_label],return_counts=True)[1])]
    # select features which best splits the dataset
    for feature in features:
        item_values=[infogain(data,feature,class_label)]
    best_feature_index=np.argmax(item_values)
    best_feature=features[best_feature_index]
    
   # create tree struct
    tree={best_feature:{}}
  # remove the feature with best information gain
    features=[i for i in features if i!=best_feature]
 
  #form subtrees by calling ID3 function recursively
    for value in np.unique(data[best_feature]):
        value=value
        sub_data=data.where(data[best_feature]==value).dropna()
        subtree=ID3(sub_data,dataset,features,class_label,parent_node_class)
        
        #add subtree
        tree[best_feature][value]=subtree
    return (tree)
    
  

In [25]:
tree=ID3(trdata,trdata,trdata.columns[:-1])
pprint(tree)


{'fixed acidity': {0: {'volatile acidity': {0: {'citric acid': {0: 1.0,
                                                                1: {'residual sugar': {0: 1.0,
                                                                                       1: {'chlorides': {0: 1.0,
                                                                                                         3: {'free sulfur dioxide': {0: 0.0,
                                                                                                                                     2: 1.0}}}},
                                                                                       2: 1.0,
                                                                                       3: 1.0}},
                                                                2: {'residual sugar': {0: {'chlorides': {0: {'free sulfur dioxide': {0: 2.0,
                                                                                                     

In [26]:
def predict(query,tree,default=1):
    for key in list(query.keys()):
        if key in list(tree.keys()):
            try:
                result=tree[key][query[key]]
            except:
                return default
            result=tree[key][query[key]]
            if isinstance(result,dict):
                return predict(query,result)
            else:
                return result

In [27]:
def test(data,tree):
  # create new query instances by simply removing the target feature column from original dataset & convert into a dictionary
    queries=data.iloc[:,:-1].to_dict(orient="records")
  
  # create an empty dataframe in which prediction of tree are stored
    predicted= pd.DataFrame(columns=["predicted"])
    
  # calculating prediction accuracy
    for i in range(len(data)):
        predicted.loc[i,"predicted"]=predict(queries[i],tree,1.0)
    print("Accuracy of the prediction : ",(np.sum(predicted["predicted"]==data["quality"])/len(data))*100,'%')
    
    

In [28]:
test(tsdata,tree)

Accuracy of the prediction :  83.75 %


In [29]:
#decision tree implementation using libraries

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier,export_text
from sklearn.metrics import classification_report,confusion_matrix

In [30]:
x=dataset.drop('quality',axis=1)
y=dataset['quality']

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [32]:
classifier=DecisionTreeClassifier()
classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [33]:
y_pred=classifier.predict(x_test)

In [34]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.22      0.12      0.15        17
           5       0.67      0.70      0.69       132
           6       0.62      0.61      0.62       125
           7       0.52      0.57      0.55        40
           8       0.17      0.25      0.20         4

    accuracy                           0.61       320
   macro avg       0.37      0.38      0.37       320
weighted avg       0.60      0.61      0.60       320



In [35]:
target=list(dataset['quality'].unique())
feature_names=list(x.columns)
r=export_text(classifier,feature_names=feature_names)
print(r)

|--- alcohol <= 10.25
|   |--- sulphates <= 0.56
|   |   |--- chlorides <= 0.07
|   |   |   |--- density <= 1.00
|   |   |   |   |--- total sulfur dioxide <= 10.50
|   |   |   |   |   |--- pH <= 3.28
|   |   |   |   |   |   |--- class: 6
|   |   |   |   |   |--- pH >  3.28
|   |   |   |   |   |   |--- class: 5
|   |   |   |   |--- total sulfur dioxide >  10.50
|   |   |   |   |   |--- residual sugar <= 1.30
|   |   |   |   |   |   |--- class: 7
|   |   |   |   |   |--- residual sugar >  1.30
|   |   |   |   |   |   |--- class: 5
|   |   |   |--- density >  1.00
|   |   |   |   |--- chlorides <= 0.06
|   |   |   |   |   |--- free sulfur dioxide <= 5.50
|   |   |   |   |   |   |--- fixed acidity <= 9.05
|   |   |   |   |   |   |   |--- class: 4
|   |   |   |   |   |   |--- fixed acidity >  9.05
|   |   |   |   |   |   |   |--- class: 6
|   |   |   |   |   |--- free sulfur dioxide >  5.50
|   |   |   |   |   |   |--- class: 5
|   |   |   |   |--- chlorides >  0.06
|   |   |   |   |   |---

In [36]:

print(confusion_matrix(y_test, y_pred))

[[ 0  0  1  1  0  0]
 [ 0  2  9  4  2  0]
 [ 1  5 93 28  4  1]
 [ 0  1 32 76 13  3]
 [ 0  1  3 12 23  1]
 [ 0  0  0  1  2  1]]


In [37]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(classifier, x_train, y_train, cv=3))

[0.55269321 0.56807512 0.53521127]


In [38]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [39]:
x=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]

k=3
kfold=KFold(n_splits=k,random_state=None)
model=LogisticRegression(solver='liblinear')

acc_score=[]

for train_index,test_index in kfold.split(x):
    x_train,x_test=x.iloc[train_index,:],x.iloc[test_index,:]
    y_train,y_test=y[train_index],y[test_index]
    
    model.fit(x_train,y_train)
    pred_values=model.predict(x_test)
    
    acc=accuracy_score(pred_values,y_test)
    acc_score.append(acc)
    
avg_acc_score=sum(acc_score)/k




In [40]:
print('Accuracy of each fold : '.format(acc_score))
print('Average accuracy : '.format(avg_acc_score))

Accuracy of each fold : 
Average accuracy : 
